<script type="text/mm-instantsearch-lazy">
    window.instantSearchConfig.instantsearchAdapter = new TypesenseInstantSearchAdapter({
        server: {
            apiKey: window.instantSearchConfig.apiKey,
            nodes: [{
                host: window.instantSearchConfig.host,
                path: window.instantSearchConfig.path,
                protocol: window.instantSearchConfig.protocol
            }],
            cacheSearchResultsForSeconds: window.instantSearchConfig.cacheSearchResultsForSeconds,
        },
        additionalSearchParameters: {
            query_by: 'sku,name,meta,category_names,description,short_description',
            query_by_weights: '1,8,5,4,1,1',
            text_match_type: 'max_score',
            prioritize_exact_match: true,
            drop_tokens_threshold: 1,
            drop_tokens_mode: "both_sides:3",
            infix: 'fallback,off,off,off,off,off',
            highlight_full_fields: '*',
            per_page: 96,
            facet_by: ['category_names', ...window.instantSearchConfig.facetBy].join(','),
            stopwords: "stopwords",
            exhaustive_search: window.instantSearchConfig.exhaustiveSearch,
        }
    });
</script>