<?php
/** @var MM_Search_Block_Instantsearch $this */
/** @var MM_Search_Helper_Data $_helper */
$_helper = $this->helper('mm_search');
?>
<script type="text/mm-instantsearch-lazy">
    window.instantSearchConfig = {
        apiKey: '<?php echo $_helper->getSearchOnlyApiKey() ?>',
        <?php if($_helper->isProxyEnabled()) : ?>
            protocol: window.location.protocol.replace(':', ''),
            host: window.location.hostname,
            port: window.location.port,
            path: '<?php echo $this->getProxyPath() ?>',
        <?php else : ?>
            protocol: '<?php echo $_helper->getProtocol() ?>',
            host: '<?php echo $_helper->getHost() ?>',
            port: '<?php echo $_helper->getPort() ?>',
            path: '',
        <?php endif; ?>
        collectionName: '<?php echo $_helper->getCollectionName() ?>',
        queriesCollection: '<?php echo $_helper->getCollectionName() ?>-product_queries',
        storeCode: '<?php echo Mage::app()->getStore()->getCode() ?>',
        useStoreCode: <?php echo Mage::getStoreConfigFlag('web/url/use_store') ? 'true' : 'false' ?>,
        facetBy: <?php echo json_encode($this->getFacetFields()) ?>,
        swatches: <?php echo json_encode($this->getSwatchData()) ?>,
        cacheSearchResultsForSeconds: <?php echo $_helper->getCacheLifetime() ?>,
        exhaustiveSearch: <?php echo $_helper->isExhaustiveSearchEnabled() ? 'true' : 'false' ?>,
        placeholderUrl: '<?php echo $this->getSkinUrl('images/catalog/product/placeholder/image.jpg') ?>',
    };
</script>
