<?php
/** @var MM_Search_Block_Searchbox $this */

/** @var MM_Search_Helper_Data $_helper */
$_helper = $this->helper('mm_search');
?>
<script>
    window.instantSearchConfig = {
        apiKey: '<?php echo $_helper->getSearchOnlyApiKey() ?>',
        <?php if($_helper->isProxyEnabled()) : ?>
            protocol: window.location.protocol.replace(':', ''),
            host: window.location.hostname,
            port: window.location.port,
            path: '<?php echo $this->getProxyPath() ?>',
        <?php else : ?>
            protocol: '<?php echo $_helper->getProtocol() ?>',
            host: '<?php echo $_helper->getHost() ?>',
            port: '<?php echo $_helper->getPort() ?>',
            path: '',
        <?php endif; ?>
        collectionName: '<?php echo $_helper->getCollectionName() ?>',
        storeCode: '<?php echo Mage::app()->getStore()->getCode() ?>',
        facetBy: <?php echo json_encode($this->getFacetFields()) ?>,
        cacheSearchResultsForSeconds: <?php echo $_helper->getCacheLifetime() ?>,
    };

    <?php switch ($_helper->getEngineType()) {
        case 'typesense': ?>
            window.instantSearchConfig.instantsearchAdapter = new TypesenseInstantSearchAdapter({
                server: {
                    apiKey: window.instantSearchConfig.apiKey,
                    nodes: [{
                        host: window.instantSearchConfig.host,
                        path: window.instantSearchConfig.path,
                        protocol: window.instantSearchConfig.protocol
                    }],
                    cacheSearchResultsForSeconds: window.instantSearchConfig.cacheSearchResultsForSeconds,
                },
                additionalSearchParameters: {
                    query_by: 'name,short_description,sku',
                    highlight_full_fields: 'name,short_description,sku',
                    per_page: 12,
                    facet_by: ['category_names', ...window.instantSearchConfig.facetBy].join(','),
                }
            });
        <?php 
            break;
        case 'meilisearch': ?>
            window.instantSearchConfig.instantsearchAdapter = instantMeiliSearch(
                window.instantSearchConfig.protocol + '://' + window.instantSearchConfig.host + window.instantSearchConfig.path,
                window.instantSearchConfig.apiKey
            );        
            /* const meilisearchAdapter = instantMeiliSearch(
                "http://localhost:7700",
                window.instantSearchConfig.apiKey
            ); */
    <?php break; 
    } ?>
</script>

<div class="typesense-search-wrapper">
    <div id="search_mini_form">
        <input type="text" id="search" name="q" class="input-text" placeholder="<?php echo $this->__('Search entire store here...') ?>" />
    </div>

    <div id="typesense-overlay" class="typesense-overlay">
        <div class="typesense-overlay-header">
            <a class="logo" href="<?php echo $this->getUrl('') ?>">
                <img src="<?php echo $this->getLogoSrc() ?>" alt="<?php echo $this->getLogoAlt() ?>" class="large" />
                <img src="<?php echo $this->getLogoSrcSmall() ?>" alt="<?php echo $this->getLogoAlt() ?>" class="small" />
            </a>
            <div id="typesense-searchbox"></div>
            <button class="typesense-close-btn">&times;</button>
        </div>
        
        <div class="typesense-overlay-content">            
            <div class="typesense-main-content">
                <div class="block-layered-nav">
                    <div class="block-content toggle-content">
                        <p class="block-subtitle block-subtitle--filter">Filter</p>    
                        <dl class="typesense-facets">
                            <dt><?php echo $this->__('Category'); ?></dt>
                            <dd id="typesense-categories"></dd>
                            
                            <?php foreach ($this->getFacetFields() as $value) : ?>
                                <dt><?php echo strtoupper($value); ?></dt>
                                <dd id="typesense-<?php echo $value ?>"></dd>
                            <?php endforeach; ?>

                            <?php /*
                            <div class="filters-actions">
                                <div id="typesense-clear-refinements"></div>
                                <button type="button" class="show-results-btn"><?php echo $this->__('Show results') ?></button>
                            </div>
                            */ ?>
                        </dl>
                    </div>
                </div>
                
                <div class="typesense-results">
                    
                    <div class="typesense-top-bar">
                        <div id="typesense-stats"></div>
                        <div style="display: flex; gap: 10px;">
                            <div id="typesense-per-page"></div>
                            <div id="typesense-sort-by"></div>
                        </div>
                    </div>
                    
                    <div id="typesense-hits"></div>
